spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    #docker run --name postgres-postnl-db -e POSTGRES_USER=compose-postgres -e POSTGRES_PASSWORD=compose-postgres -p 5433:5432 -d postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: compose-postgres
    password: compose-postgres
    initialization-mode: always